# Docker Compose for local development
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vicentech-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./docker/php.ini:/usr/local/etc/php/conf.d/app.ini
    ports:
      - "8000:8000"
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=vicentech
      - DB_USERNAME=vicentech
      - DB_PASSWORD=password
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:15
    container_name: vicentech-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=vicentech
      - POSTGRES_USER=vicentech
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7-alpine
    container_name: vicentech-redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  postgres_data:
