# Netlify configuration for React frontend
# This file configures the frontend deployment on Netlify

[build]
  # Build command for Netlify
  command = "npm run build"
  
  # Directory to publish
  publish = "public"

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Build environment variables
  NODE_ENV = "production"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# API proxy to backend
[[redirects]]
  from = "/api/*"
  to = "https://your-backend-url.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/sanctum/*"
  to = "https://your-backend-url.onrender.com/sanctum/:splat"
  status = 200
  force = true
