# Frontend Build Configuration for Netlify

# This file contains the build configuration for deploying the React frontend to Netlify

# Build command
npm run build

# Publish directory
public

# Node version
18

# Environment variables for build
NODE_ENV=production

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API proxy configuration
# Update these URLs with your actual Render backend URL
[[redirects]]
  from = "/api/*"
  to = "https://vicentech-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/sanctum/*"
  to = "https://vicentech-backend.onrender.com/sanctum/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/login"
  to = "https://vicentech-backend.onrender.com/login"
  status = 200
  force = true

[[redirects]]
  from = "/logout"
  to = "https://vicentech-backend.onrender.com/logout"
  status = 200
  force = true

[[redirects]]
  from = "/csrf-token"
  to = "https://vicentech-backend.onrender.com/csrf-token"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://vicentech-backend.onrender.com;"
