services:
  - type: web
    name: vicentech-backend
    env: docker
    plan: starter
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: postgresql
      - key: CACHE_DRIVER
        value: redis
      - key: SESSION_DRIVER
        value: redis
      - key: QUEUE_CONNECTION
        value: redis
      - key: REDIS_HOST
        fromDatabase:
          name: vicentech-redis
          property: host
      - key: REDIS_PORT
        fromDatabase:
          name: vicentech-redis
          property: port
      - key: REDIS_PASSWORD
        fromDatabase:
          name: vicentech-redis
          property: password

databases:
  - name: vicentech-postgres
    plan: starter
  - name: vicentech-redis
    plan: starter
